---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/docker-awscli
  commands:
  - /usr/local/bin/wait
  - docker build -t $${IMAGE_NAME}:$${DRONE_COMMIT_SHA} . --no-cache
  when:
    event:
    - push
    - tag

- name: push_latest
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/docker-awscli
    tags:
    - ${DRONE_COMMIT_SHA}
    - latest
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+docker_awscli
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

- name: push_tag
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/docker-awscli
    REGISTRY: quay.io
    DOCKER_USERNAME: ukhomeofficedigital+docker_awscli
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - /usr/local/bin/wait
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_PASSWORD}" $${REGISTRY}
  - docker tag $${IMAGE_NAME}:$${DRONE_COMMIT_SHA} $${IMAGE_NAME}:$${DRONE_TAG}
  - docker push $${IMAGE_NAME}:$${DRONE_COMMIT_SHA}
  - docker push $${IMAGE_NAME}:$${DRONE_TAG}
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
